snap: don't abort on `swapon` failures
This is needed when building snap on LXD containers.

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -47,7 +47,10 @@ parts:
       fallocate -l 2G /tmp/swap
       chmod 0600 /tmp/swap
       mkswap /tmp/swap
-      swapon /tmp/swap
+      if ! swapon /tmp/swap; then
+        echo "Could not enable swap file, continuing anyway"
+        rm /tmp/swap
+      fi
 
       cabal update
       cabal install -j
